Box,0,ground,240,355
Box,1,output 0.2,130,399
Box,2,input ./sample-44k.wav 0.2,264,69
Box,3,diode,213,176
Box,4,diode,452,181
Box,5,diode,104,175
Box,6,diode,345,180
Connection,5,2,1,0,analog
Connection,3,2,0,0,analog
Connection,6,2,0,1,analog
Connection,2,4,1,1,analog
Connection,1,3,0,1,analog
Connection,1,6,0,1,analog
Connection,1,5,1,0,analog
Connection,1,4,1,0,analog
Connection,1,0,1,0,analog
